---
- name: ensure service is stopped
  systemd:
    name: "{{ systemd_service_name }}"
    state: stopped
    enabled: no

- name: remove service {{ systemd_service_name }}
  file:
    path: /etc/systemd/system/{{ systemd_service_name }}.service
    state: absent
