---
- name: Destroy GCP Cluster
  command: gcloud beta container --project {{ gcp_project }} clusters delete {{ gcp_cluster_name }}
    --quiet
    --zone {{ gcp_location }}
    --account {{ gcp_service_account }}
