---
- name: Install helm
  shell: curl -fsSL https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash -s -- --version "v{{ helm_version }}"
  args:
    warn: false
    creates: /usr/local/bin/helm
  when: helm_install_binary

- name: Create service account for tiller
  k8s:
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: tiller
        namespace: kube-system
  when: helm_install_tiller

- name: Create cluster role binding for tiller
  k8s:
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: tiller
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: tiller
          namespace: kube-system
  when: helm_install_tiller

- name: Init helm
  command: "{{ helm_bin }} init --service-account tiller --wait --tiller-image gcr.io/kubernetes-helm/tiller:v{{ helm_tiller_version }}"
  changed_when: yes
  when: helm_install_tiller
