---
- name: template service {{ systemd_service_name }}
  template:
    src: service.j2
    dest: /etc/systemd/system/{{ systemd_service_name }}.service
  register: result

- name: reload daemon to have the unit file known by systemd
  systemd:
    name: "{{ systemd_service_name }}"
    daemon_reload: yes
  when:
    - result is changed

- name: start service {{ systemd_service_name }}
  systemd:
    name: "{{ systemd_service_name }}"
    state: restarted
    enabled: yes
  when:
    - result is changed
    - systemd_start | bool

- name: ensure service is started
  systemd:
    name: "{{ systemd_service_name }}"
    state: started
    enabled: yes
  when: systemd_start | bool
