---
- name: template service {{ systemd_service_name }}
  template:
    src: service.j2
    dest: /etc/systemd/system/{{ systemd_service_name }}.service
  register: service_unit_result

- name: reload daemon to have the unit file known by systemd
  systemd:
    name: "{{ systemd_service_name }}"
    daemon_reload: yes
  when:
    - service_unit_result is changed

- name: pre-pull docker image
  command: docker pull {{ systemd_docker_image_name }}:{{ systemd_docker_image_tag }}
  register: pull_image_result
  changed_when: "'Downloaded newer image' in pull_image_result.stdout"

- name: start service {{ systemd_service_name }}
  systemd:
    name: "{{ systemd_service_name }}"
    state: restarted
    enabled: yes
  when:
    - service_unit_result is changed or pull_image_result is changed or systemd_external_config_changed | bool
    - systemd_start | bool
  register: service_restart_result
  until: service_restart_result is success
  retries: 2
  delay: 10

- name: ensure service is started
  systemd:
    name: "{{ systemd_service_name }}"
    state: started
    enabled: yes
  when: systemd_start | bool
