---
# on the Vagrant Ubuntu boxes we often encounter issues with DNS, such that package repositories cannot be resolved.
# running apt will then show something like this, failing:
#
# 43 packages can be upgraded. Run 'apt list --upgradable' to see them.
# W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/cosmic/InRelease  Temporary failure resolving 'us.archive.ubuntu.com'
# W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/cosmic-updates/InRelease  Temporary failure resolving 'us.archive.ubuntu.com'
# W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/cosmic-backports/InRelease  Temporary failure resolving 'us.archive.ubuntu.com'
# W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/cosmic-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
# W: Some index files failed to download. They have been ignored, or old ones used instead.
#
# we found the reason for this is that the Vagrant box has DNS servers from the US configured.
#
# additionally, we cannot resolve the other vagrant machines (e.g. oob-mgmt-server, metal-api...) from an Ubuntu machine with systemd-resolved
# for some reason. We therefore disable system-resolved as a workaround (if someone wants to volunteer and find a better solution, feel free!)
# and just write the default DNS to /etc/resolved.conf directly, which makes name resolution working quite adequately.
#
# however, resolving a vagrant machine like metal-api with nslookup leads to a servfail error even though it works perfectly fine with dig.
- name: Remove /etc/resolv.conf symbolic link to apply a custom configuration.
  raw: rm -f /etc/resolv.conf

- name: Provide a custom resolv.conf to have DNS reliably working.
  raw: echo 'nameserver 192.168.121.1' > /etc/resolv.conf;

- name: Put marker file that DNS was cleaned to stay idempotent.
  raw: touch ~/.ansible_vagrantprep_dns
