---
- name: Test if DNS was already cleaned
  raw: ls ~/.ansible_vagrantprep_dns
  changed_when: false
  failed_when: false
  register: result

- name: Clean DNS
  import_tasks: clean_dns.yaml
  when: result.rc != 0

- name: Ensure python is installed
  raw: apt update && apt install -y python

- name: Remove weird entry in /etc/hosts for localhost
  lineinfile:
    path: /etc/hosts
    state: absent
    regexp: "^127.0.1.1"

# now back to less hacky, normal mode...
- name: Gather facts
  action: setup

- name: Remove swapfile from /etc/fstab
  mount:
    name: none
    fstype: swap
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
