---
- name: Create systemd docker service directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Template Docker startup options
  template:
    src: startup_options.j2
    dest: /etc/systemd/system/docker.service.d/startup_options.conf
  register: result

- name: Reload systemd daemon if template is changed
  systemd:
    name: docker
    state: restarted
    daemon_reload: true
  when: result is changed

- name: Wait for open Docker port
  wait_for:
    port: 2376
    delay: 3
    timeout: 60
