name: Push on master

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Push
    runs-on: ubuntu-latest
    steps:
    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
